# comment to trigger ci
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
tasks:
  - init: |
      # warning: binary cache 'https://cache.nixos.org' is for Nix stores with prefix '/nix/store', not '/workspace/nix/store'
      # cachix use fedimint
      nix develop
      cargo build
    env:
      NIX_STORE_DIR: /workspace/nix/store
