# comment to trigger ci
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
tasks:
  - init:
      cachix use fedimint
      nix develop
      cargo build
    env:
      NIX_STORE_DIR: /workspace/nix/store
