# comment to trigger ci
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
tasks:
  - init: |
      cachix use fedimint
      cargo build
