[package]
name = "fedimint-setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.11.1", features = ["with-axum"] }
axum-core = "0.1"
http = "0.2"
http-body = "0.4"
askama_axum = "0.1.0"

axum = { version = "0.4", default-features = false }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }

fedimint-api = { path = "../fedimint-api", features = ["rocksdb"] }
