[package]
name = "fedimint-derive"
version = "0.2.2-rc3"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-derive provides helper macros for serialization."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[lib]
proc-macro = true
name = "fedimint_derive"
path = "src/lib.rs"

[features]
diagnostics = []

[dependencies]
itertools = "0.11.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
