[package]
name = "fedimint-metrics"
version = "0.2.2-rc4"
edition = "2021"
license = "MIT"
description = "fedimint-metrics allows exporting prometheus metrics from Fedimint."
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_metrics"
path = "./src/lib.rs"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
axum = "0.6.18"
fedimint-core = { version = "0.2.2-rc4", path = "../fedimint-core" }
lazy_static = "1.4.0"
prometheus = "0.13.3"
tokio = "1"
tracing = "0.1.37"
