[package]
name = "fedimint-rocksdb"
version = "0.2.2-rc7"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-rocksdb provides a rocksdb-backed database implementation for Fedimint."
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_rocksdb"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
fedimint-core = { version = "0.2.2-rc7", path = "../fedimint-core" }
futures = "0.3.24"
rocksdb = { version = "0.21.0" }
tracing = "0.1.37"

[dev-dependencies]
tempfile = "3.4.0"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }

[target.'cfg(not(target_family="wasm"))'.dependencies]
tokio = { version = "1.26.0", features = ["rt", "rt-multi-thread", "sync", "time"] }
