[package]
name = "minimint"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.42"
bincode = "1.3.1"
bitcoin = "0.27.0"
clap = { version = "3.1.18", features = ["derive"] }
futures = "0.3.9"
hbbft = { git = "https://github.com/fedimint/hbbft", branch = "minimint" }
hex = "0.4.2"
itertools = "0.10.0"
minimint-api = { path = "../minimint-api" }
minimint-derive = { path = "../minimint-derive" }
minimint-shared = { path = "../minimint-shared" }
minimint-ln = { path = "../modules/minimint-ln" }
minimint-mint = { path = "../modules/minimint-mint" }
minimint-wallet = { path = "../modules/minimint-wallet" }
rand = "0.6.5"
rayon = "1.5.0"
secp256k1-zkp = { git = "https://github.com/fedimint/rust-secp256k1-zkp", branch = "minimint", features = [ "global-context", "bitcoin_hashes" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
serde_json = "1.0.61"
sha3 = "0.9.1"
sled = "0.34.6"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.23"
tide = "0.16.0"
tokio = { version = "1.0.1", features = ["full"] }
tokio-util = { version = "0.6.0", features = [ "compat" ] }
tracing ="0.1.22"
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }

[dev-dependencies]
bitcoincore-rpc = "0.14.0"
cln-rpc = "0.1"
clightningrpc = "0.2.0"
lightning-invoice = "0.14.0"
mint-client = { path = "../mint-client" }
ln-gateway = { path = "../ln-gateway" }
lightning = "0.0.106"
assert_matches = "1.5.0"
