[package]
name = "fedimint-aead"
version = "0.2.2-rc4"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "aead utilities on top of ring "
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_aead"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.65"
argon2 = { version = "0.5.0", features = ["password-hash", "alloc"] }
ring = "0.17.5"
hex = "0.4.3"
rand = "0.8"
