[package]
name = "fedimint-build"
version = "0.2.2-rc7"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint is the main consensus code for processing transactions and REST API"
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[lib]
name = "fedimint_build"
path = "src/lib.rs"

[dependencies]
serde_json = "1.0.108"
